//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// C:\Proyectos\azure-mobile-services\sdk\Managed\src\Microsoft.WindowsAzure.MobileServices.SQLiteStore\Properties\Resources.tt
// C:\Proyectos\azure-mobile-services\sdk\Managed\src\Microsoft.WindowsAzure.MobileServices.SQLiteStore\Properties
// 51
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.MobileServices.SQLiteStore.Properties
{    
    using System;
    using System.Reflection;
    using System.Resources;        
    using System.Collections.Generic;

    /// <summary>
    ///  Resource manager for Resources
    /// </summary>    
    public static class Resources    {
                /// <summary>
        ///  Localized value for Platform_AssemblyNotFound.
        ///  Default value: 'A Windows Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both {0} and the following platform-specific assembly: {1}.' 
        /// </summary>
        public static string Platform_AssemblyNotFound { get { return @"A Windows Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both {0} and the following platform-specific assembly: {1}."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_ColumnNotDefined.
        ///  Default value: 'Column with name '{0}' is not defined on the local table '{1}'.' 
        /// </summary>
        public static string SQLiteStore_ColumnNotDefined { get { return @"Column with name '{0}' is not defined on the local table '{1}'."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_DefineAfterInitialize.
        ///  Default value: 'Cannot define a table after the store has been initialized.' 
        /// </summary>
        public static string SQLiteStore_DefineAfterInitialize { get { return @"Cannot define a table after the store has been initialized."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_DefineTableEmptyCtorNotDefined.
        ///  Default value: 'The generic type T does not have parameterless constructor.' 
        /// </summary>
        public static string SQLiteStore_DefineTableEmptyCtorNotDefined { get { return @"The generic type T does not have parameterless constructor."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_DefineTableTNotAnObject.
        ///  Default value: 'The generic type T is not an object.' 
        /// </summary>
        public static string SQLiteStore_DefineTableTNotAnObject { get { return @"The generic type T is not an object."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_InvalidIdentifier.
        ///  Default value: ''{0}' is not a valid identifier. Identifiers must be under 128 characters in length, start with a letter or underscore, and can contain only alpha-numeric and underscore characters.' 
        /// </summary>
        public static string SQLiteStore_InvalidIdentifier { get { return @"'{0}' is not a valid identifier. Identifiers must be under 128 characters in length, start with a letter or underscore, and can contain only alpha-numeric and underscore characters."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_JTokenNotSupported.
        ///  Default value: 'Property of type '{0}' is not supported.' 
        /// </summary>
        public static string SQLiteStore_JTokenNotSupported { get { return @"Property of type '{0}' is not supported."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_QueryExecutionFailed.
        ///  Default value: 'Query execution failed with result: '{0}'.' 
        /// </summary>
        public static string SQLiteStore_QueryExecutionFailed { get { return @"Query execution failed with result: '{0}'."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_TableNotDefined.
        ///  Default value: 'Table with name '{0}' is not defined.' 
        /// </summary>
        public static string SQLiteStore_TableNotDefined { get { return @"Table with name '{0}' is not defined."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_TooManyColumns.
        ///  Default value: 'The number of fields per entity in an upsert operation is limited to {0}.' 
        /// </summary>
        public static string SQLiteStore_TooManyColumns { get { return @"The number of fields per entity in an upsert operation is limited to {0}."; } }
        /// <summary>
        ///  Localized value for SQLiteStore_ValueTypeNotSupported.
        ///  Default value: 'Value of type '{0}' is not supported.' 
        /// </summary>
        public static string SQLiteStore_ValueTypeNotSupported { get { return @"Value of type '{0}' is not supported."; } }
         
    }
}