//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// C:\Proyectos\azure-mobile-services\sdk\Managed\src\Microsoft.WindowsAzure.MobileServices\Resources.tt
// C:\Proyectos\azure-mobile-services\sdk\Managed\src\Microsoft.WindowsAzure.MobileServices
// 51
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.MobileServices
{    
    using System;
    using System.Reflection;
    using System.Resources;        
    using System.Collections.Generic;

    /// <summary>
    ///  Resource manager for Resources
    /// </summary>    
    public static class Resources    {
                /// <summary>
        ///  Localized value for IApplicationStorage_NullOrWhitespaceSettingName.
        ///  Default value: 'An application setting name must be provided. Null, empty or whitespace only names are not allowed.' 
        /// </summary>
        public static string IApplicationStorage_NullOrWhitespaceSettingName { get { return @"An application setting name must be provided. Null, empty or whitespace only names are not allowed."; } }
        /// <summary>
        ///  Localized value for IAuthenticationBroker_AuthenticationCanceled.
        ///  Default value: 'Authentication was cancelled by the user.' 
        /// </summary>
        public static string IAuthenticationBroker_AuthenticationCanceled { get { return @"Authentication was cancelled by the user."; } }
        /// <summary>
        ///  Localized value for IAuthenticationBroker_AuthenticationFailed.
        ///  Default value: 'Authentication failed with HTTP response code {0}.' 
        /// </summary>
        public static string IAuthenticationBroker_AuthenticationFailed { get { return @"Authentication failed with HTTP response code {0}."; } }
        /// <summary>
        ///  Localized value for MobileServiceClient_EmptyArgument.
        ///  Default value: '{0} cannot be null, empty or only whitespace.' 
        /// </summary>
        public static string MobileServiceClient_EmptyArgument { get { return @"{0} cannot be null, empty or only whitespace."; } }
        /// <summary>
        ///  Localized value for MobileServiceClient_ErrorMessage.
        ///  Default value: 'The request could not be completed.  ({0})' 
        /// </summary>
        public static string MobileServiceClient_ErrorMessage { get { return @"The request could not be completed.  ({0})"; } }
        /// <summary>
        ///  Localized value for IAuthenticationBroker_InvalidLoginResponse.
        ///  Default value: 'Invalid format of the authentication response.' 
        /// </summary>
        public static string IAuthenticationBroker_InvalidLoginResponse { get { return @"Invalid format of the authentication response."; } }
        /// <summary>
        ///  Localized value for MobileServicesAuthentication_LoginAlreadyInProgress.
        ///  Default value: 'Cannot start a login operation because login is already in progress.' 
        /// </summary>
        public static string MobileServicesAuthentication_LoginAlreadyInProgress { get { return @"Cannot start a login operation because login is already in progress."; } }
        /// <summary>
        ///  Localized value for IAuthenticationBroker_LoginFailed.
        ///  Default value: 'Login failed: {0}' 
        /// </summary>
        public static string IAuthenticationBroker_LoginFailed { get { return @"Login failed: {0}"; } }
        /// <summary>
        ///  Localized value for MobileServiceTableUrlBuilder_InvalidParameterBeginsWithDollarSign.
        ///  Default value: '{0} is an invalid user-defined query string parameter. User-defined query string parameters must not begin with a \'$\'.' 
        /// </summary>
        public static string MobileServiceTableUrlBuilder_InvalidParameterBeginsWithDollarSign { get { return @"{0} is an invalid user-defined query string parameter. User-defined query string parameters must not begin with a \'$\'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_InsertWithExistingId.
        ///  Default value: 'Cannot insert if the {0} member is already set.' 
        /// </summary>
        public static string MobileServiceTable_InsertWithExistingId { get { return @"Cannot insert if the {0} member is already set."; } }
        /// <summary>
        ///  Localized value for Platform_AssemblyNotFound.
        ///  Default value: 'A Microsoft Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both {0} and the following platform-specific assembly: {1}.' 
        /// </summary>
        public static string Platform_AssemblyNotFound { get { return @"A Microsoft Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both {0} and the following platform-specific assembly: {1}."; } }
        /// <summary>
        ///  Localized value for Platform_InstantiationFailed.
        ///  Default value: 'Failed to instantiate the platform implementation of {0} from the assembly {1} due to the following error: {2}' 
        /// </summary>
        public static string Platform_InstantiationFailed { get { return @"Failed to instantiate the platform implementation of {0} from the assembly {1} due to the following error: {2}"; } }
        /// <summary>
        ///  Localized value for FilterBuildingExpressionVisitor_MemberUnsupported.
        ///  Default value: 'The member '{0}' is not supported in the 'Where' Mobile Services query expression '{1}'.' 
        /// </summary>
        public static string FilterBuildingExpressionVisitor_MemberUnsupported { get { return @"The member '{0}' is not supported in the 'Where' Mobile Services query expression '{1}'."; } }
        /// <summary>
        ///  Localized value for FilterBuildingExpressionVisitor_OperatorUnsupported.
        ///  Default value: 'The operator '{0}' is not supported in the 'Where' Mobile Services query expression '{1}'.' 
        /// </summary>
        public static string FilterBuildingExpressionVisitor_OperatorUnsupported { get { return @"The operator '{0}' is not supported in the 'Where' Mobile Services query expression '{1}'."; } }
        /// <summary>
        ///  Localized value for FilterBuildingExpressionVisitor_UnsupportedInWhereExpression.
        ///  Default value: ''{0}' is not supported in a 'Where' Mobile Services query expression.' 
        /// </summary>
        public static string FilterBuildingExpressionVisitor_UnsupportedInWhereExpression { get { return @"'{0}' is not supported in a 'Where' Mobile Services query expression."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableQueryTranslator_SingleIntegerOnly.
        ///  Default value: ''{0}' Mobile Services query expressions must consist of a single integer, not '{1}'.' 
        /// </summary>
        public static string MobileServiceTableQueryTranslator_SingleIntegerOnly { get { return @"'{0}' Mobile Services query expressions must consist of a single integer, not '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableQueryTranslator_MembersOnlyInExpression.
        ///  Default value: ''{0}' Mobile Services query expressions must consist of members only, not '{1}'.' 
        /// </summary>
        public static string MobileServiceTableQueryTranslator_MembersOnlyInExpression { get { return @"'{0}' Mobile Services query expressions must consist of members only, not '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableQueryTranslator_UnsupportedExpression.
        ///  Default value: 'Expression '{1}' is not a supported '{0}' Mobile Services query expression.' 
        /// </summary>
        public static string MobileServiceTableQueryTranslator_UnsupportedExpression { get { return @"Expression '{1}' is not a supported '{0}' Mobile Services query expression."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableSerializer_CannotDeserializeValue.
        ///  Default value: 'Cannot deserialize value {0} into '{1}.{2}'.' 
        /// </summary>
        public static string MobileServiceTableSerializer_CannotDeserializeValue { get { return @"Cannot deserialize value {0} into '{1}.{2}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableSerializer_MissingRequiredMember.
        ///  Default value: 'Cannot deserialize type '{0}' because the JSON object did not have required member(s) '{1}'.' 
        /// </summary>
        public static string MobileServiceTableSerializer_MissingRequiredMember { get { return @"Cannot deserialize type '{0}' because the JSON object did not have required member(s) '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableSerializer_NeedObject.
        ///  Default value: 'Expected a JSON object to deserialize, not '{0}'.' 
        /// </summary>
        public static string MobileServiceTableSerializer_NeedObject { get { return @"Expected a JSON object to deserialize, not '{0}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableSerializer_UnknownType.
        ///  Default value: 'Cannot serialize member '{0}' of type '{1}' declared on type '{2}'.' 
        /// </summary>
        public static string MobileServiceTableSerializer_UnknownType { get { return @"Cannot serialize member '{0}' of type '{1}' declared on type '{2}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_ExpectedArray.
        ///  Default value: 'Could not get an array from response {0}.' 
        /// </summary>
        public static string MobileServiceTable_ExpectedArray { get { return @"Could not get an array from response {0}."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_NotSingleObject.
        ///  Default value: 'Could not get object from response {0}.' 
        /// </summary>
        public static string MobileServiceTable_NotSingleObject { get { return @"Could not get object from response {0}."; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_MemberNotFound.
        ///  Default value: 'No '{0}' member found on type '{1}'.' 
        /// </summary>
        public static string MobileServiceContractResolver_MemberNotFound { get { return @"No '{0}' member found on type '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_SamePropertyName.
        ///  Default value: 'Only one member may have the property name '{0}' (regardless of casing) on type '{1}'.' 
        /// </summary>
        public static string MobileServiceContractResolver_SamePropertyName { get { return @"Only one member may have the property name '{0}' (regardless of casing) on type '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_TypeWithDataMemberButNoDataContract.
        ///  Default value: 'The type '{0}' has one or members with a DataMemberAttribute, but the type itself does not have a DataContractAttribute. Use the Newtonsoft.Json.JsonPropertyAttribute in place of the DataMemberAttribute and set the PropertyName to the desired name.' 
        /// </summary>
        public static string MobileServiceContractResolver_TypeWithDataMemberButNoDataContract { get { return @"The type '{0}' has one or members with a DataMemberAttribute, but the type itself does not have a DataContractAttribute. Use the Newtonsoft.Json.JsonPropertyAttribute in place of the DataMemberAttribute and set the PropertyName to the desired name."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_IdNotFound.
        ///  Default value: 'Expected {0} member not found.' 
        /// </summary>
        public static string MobileServiceSerializer_IdNotFound { get { return @"Expected {0} member not found."; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_NumberOutOfRange.
        ///  Default value: 'The value {0} for member {1} is outside the valid range for numeric columns.' 
        /// </summary>
        public static string MobileServiceContractResolver_NumberOutOfRange { get { return @"The value {0} for member {1} is outside the valid range for numeric columns."; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_TypeNoDataContractButBaseWithDataContract.
        ///  Default value: 'The type '{0}' does not have a DataContractAttribute, but the type derives from the type '{1}', which does have a DataContractAttribute. If a type has a DataContractAttribute, any type that derives from that type must also have a DataContractAttribute.' 
        /// </summary>
        public static string MobileServiceContractResolver_TypeNoDataContractButBaseWithDataContract { get { return @"The type '{0}' does not have a DataContractAttribute, but the type derives from the type '{1}', which does have a DataContractAttribute. If a type has a DataContractAttribute, any type that derives from that type must also have a DataContractAttribute."; } }
        /// <summary>
        ///  Localized value for ExpressionUtility_ProjectionNotSupportedOnWindowsPhone75.
        ///  Default value: 'The Linq IQueryable Select() operation is not supported on the Windows Phone 7.5 platform.' 
        /// </summary>
        public static string ExpressionUtility_ProjectionNotSupportedOnWindowsPhone75 { get { return @"The Linq IQueryable Select() operation is not supported on the Windows Phone 7.5 platform."; } }
        /// <summary>
        ///  Localized value for MobileServiceClient_NoResponseContent.
        ///  Default value: 'The server did not provide a response with the expected content.' 
        /// </summary>
        public static string MobileServiceClient_NoResponseContent { get { return @"The server did not provide a response with the expected content."; } }
        /// <summary>
        ///  Localized value for MobileServiceJsonSerializerSettings_NullOrInvalidContractResolver.
        ///  Default value: 'The member '{0}.ContractResolver' must be set to an instance of the '{1}' class or a class that inherits from the '{1}' class.' 
        /// </summary>
        public static string MobileServiceJsonSerializerSettings_NullOrInvalidContractResolver { get { return @"The member '{0}.ContractResolver' must be set to an instance of the '{1}' class or a class that inherits from the '{1}' class."; } }
        /// <summary>
        ///  Localized value for MobileServicePrecisionCheckConverter_ReadNotSupported.
        ///  Default value: 'The {0} does not support reading JSON.' 
        /// </summary>
        public static string MobileServicePrecisionCheckConverter_ReadNotSupported { get { return @"The {0} does not support reading JSON."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_DeleteWithoutId.
        ///  Default value: 'Cannot delete if the {0} member is set to a default value.' 
        /// </summary>
        public static string MobileServiceTable_DeleteWithoutId { get { return @"Cannot delete if the {0} member is set to a default value."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_UpdateWithoutId.
        ///  Default value: 'Cannot update if the {0} member is set to a default value.' 
        /// </summary>
        public static string MobileServiceTable_UpdateWithoutId { get { return @"Cannot update if the {0} member is set to a default value."; } }
        /// <summary>
        ///  Localized value for MobileServiceClient_InnerHandlerMustBeNull.
        ///  Default value: 'The 'InnerHandler' property of the delegating handler must be null.' 
        /// </summary>
        public static string MobileServiceClient_InnerHandlerMustBeNull { get { return @"The 'InnerHandler' property of the delegating handler must be null."; } }
        /// <summary>
        ///  Localized value for HttpMessageHandlerExtensions_WrongHandlerType.
        ///  Default value: 'All message handlers except the last must be of the type '{0}'' 
        /// </summary>
        public static string HttpMessageHandlerExtensions_WrongHandlerType { get { return @"All message handlers except the last must be of the type '{0}'"; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_MultipleSystemPropertyAttributes.
        ///  Default value: 'A member can only have one system property attribute. The member '{0}' on type '{1}' has system property attributes '{2}' and '{3}'.' 
        /// </summary>
        public static string MobileServiceContractResolver_MultipleSystemPropertyAttributes { get { return @"A member can only have one system property attribute. The member '{0}' on type '{1}' has system property attributes '{2}' and '{3}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceCollection_LoadInProcess.
        ///  Default value: 'Loading of more items already in process.' 
        /// </summary>
        public static string MobileServiceCollection_LoadInProcess { get { return @"Loading of more items already in process."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_InvalidIntegerId.
        ///  Default value: 'The integer id '{0}' is not a positive integer value.' 
        /// </summary>
        public static string MobileServiceSerializer_InvalidIntegerId { get { return @"The integer id '{0}' is not a positive integer value."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_StringIdTooLong.
        ///  Default value: 'The string id '{0}' is longer than the max string id length of {1} characters.' 
        /// </summary>
        public static string MobileServiceSerializer_StringIdTooLong { get { return @"The string id '{0}' is longer than the max string id length of {1} characters."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_LookupInvalidIdType.
        ///  Default value: 'The id parameter type '{0}' is invalid for looking up items of type '{1}'.' 
        /// </summary>
        public static string MobileServiceSerializer_LookupInvalidIdType { get { return @"The id parameter type '{0}' is invalid for looking up items of type '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_IdCasingIncorrect.
        ///  Default value: 'The casing of the '{0}' property is invalid.' 
        /// </summary>
        public static string MobileServiceSerializer_IdCasingIncorrect { get { return @"The casing of the '{0}' property is invalid."; } }
        /// <summary>
        ///  Localized value for MobileServiceContractResolver_IntegerIdTypeWithSystemPropertyAttributes.
        ///  Default value: 'The type '{0}' has an integer id member and therefore can not have any members with the system property attribute '{1}'.' 
        /// </summary>
        public static string MobileServiceContractResolver_IntegerIdTypeWithSystemPropertyAttributes { get { return @"The type '{0}' has an integer id member and therefore can not have any members with the system property attribute '{1}'."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_InvalidStringId.
        ///  Default value: 'The string id '{0}' is invalid. An id must not contain any control characters or the characters "",+,?,\,/,`.' 
        /// </summary>
        public static string MobileServiceSerializer_InvalidStringId { get { return @"The string id '{0}' is invalid. An id must not contain any control characters or the characters "",+,?,\,/,`."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_NullOrEmptyStringId.
        ///  Default value: 'The id can not be null or an empty string.' 
        /// </summary>
        public static string MobileServiceSerializer_NullOrEmptyStringId { get { return @"The id can not be null or an empty string."; } }
        /// <summary>
        ///  Localized value for MobileServiceSerializer_IdTypeMismatch.
        ///  Default value: 'You might be affected by Mobile Services latest changes to support string Ids. For more details: http://go.microsoft.com/fwlink/?LinkId=330396' 
        /// </summary>
        public static string MobileServiceSerializer_IdTypeMismatch { get { return @"You might be affected by Mobile Services latest changes to support string Ids. For more details: http://go.microsoft.com/fwlink/?LinkId=330396"; } }
        /// <summary>
        ///  Localized value for MobileServiceCollection_IncrementalLoadingFailed.
        ///  Default value: 'Failed to incrementally load more items of type '{0}'. See the inner exception for details.' 
        /// </summary>
        public static string MobileServiceCollection_IncrementalLoadingFailed { get { return @"Failed to incrementally load more items of type '{0}'. See the inner exception for details."; } }
        /// <summary>
        ///  Localized value for Push_ConflictWithReservedName.
        ///  Default value: 'Template name conflicts with reserved name '{0}'.' 
        /// </summary>
        public static string Push_ConflictWithReservedName { get { return @"Template name conflicts with reserved name '{0}'."; } }
        /// <summary>
        ///  Localized value for Push_InvalidTemplateName.
        ///  Default value: 'Template name cannot contain "";"" or "":"".' 
        /// </summary>
        public static string Push_InvalidTemplateName { get { return @"Template name cannot contain "";"" or "":""."; } }
        /// <summary>
        ///  Localized value for Push_NotSupportedXMLFormatAsBodyTemplateWin8.
        ///  Default value: 'The bodyTemplate is not in accepted XML format. The first node of the bodyTemplate should be Badge/Tile/Toast, except for the wns/raw template, which needs to be an valid XML.' 
        /// </summary>
        public static string Push_NotSupportedXMLFormatAsBodyTemplateWin8 { get { return @"The bodyTemplate is not in accepted XML format. The first node of the bodyTemplate should be Badge/Tile/Toast, except for the wns/raw template, which needs to be an valid XML."; } }
        /// <summary>
        ///  Localized value for Push_BodyTemplateMustBeXml.
        ///  Default value: 'Valid XML is required for any template without a raw header.' 
        /// </summary>
        public static string Push_BodyTemplateMustBeXml { get { return @"Valid XML is required for any template without a raw header."; } }
        /// <summary>
        ///  Localized value for Push_BodyTemplateMustContainElement.
        ///  Default value: 'XML must contain an XML node of Element type.' 
        /// </summary>
        public static string Push_BodyTemplateMustContainElement { get { return @"XML must contain an XML node of Element type."; } }
        /// <summary>
        ///  Localized value for Push_TagNoCommas.
        ///  Default value: 'Tags must not contain ','.' 
        /// </summary>
        public static string Push_TagNoCommas { get { return @"Tags must not contain ','."; } }
        /// <summary>
        ///  Localized value for IAuthenticationBroker_LoginInProgress.
        ///  Default value: 'Authentication is already in progress.' 
        /// </summary>
        public static string IAuthenticationBroker_LoginInProgress { get { return @"Authentication is already in progress."; } }
        /// <summary>
        ///  Localized value for IAuthenticationBroker_NoLoginInProgress.
        ///  Default value: 'Authentication has not been started.' 
        /// </summary>
        public static string IAuthenticationBroker_NoLoginInProgress { get { return @"Authentication has not been started."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_IdMustBeString.
        ///  Default value: 'The id must be of type string.' 
        /// </summary>
        public static string MobileServiceSyncTable_IdMustBeString { get { return @"The id must be of type string."; } }
        /// <summary>
        ///  Localized value for SyncContext_NotInitialized.
        ///  Default value: 'SyncContext is not yet initialized.' 
        /// </summary>
        public static string SyncContext_NotInitialized { get { return @"SyncContext is not yet initialized."; } }
        /// <summary>
        ///  Localized value for SyncStore_FailedToUpsertItem.
        ///  Default value: 'Failed to update the item in the local store.' 
        /// </summary>
        public static string SyncStore_FailedToUpsertItem { get { return @"Failed to update the item in the local store."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableQueryDescription_UnrecognizedQueryParameter.
        ///  Default value: 'Unrecognized query parameter '{0}'.' 
        /// </summary>
        public static string MobileServiceTableQueryDescription_UnrecognizedQueryParameter { get { return @"Unrecognized query parameter '{0}'."; } }
        /// <summary>
        ///  Localized value for SyncContext_DeletePending.
        ///  Default value: 'A delete operation on the item is already in the queue.' 
        /// </summary>
        public static string SyncContext_DeletePending { get { return @"A delete operation on the item is already in the queue."; } }
        /// <summary>
        ///  Localized value for SyncContext_DuplicateInsert.
        ///  Default value: 'An insert operation on the item is already in the queue.' 
        /// </summary>
        public static string SyncContext_DuplicateInsert { get { return @"An insert operation on the item is already in the queue."; } }
        /// <summary>
        ///  Localized value for SyncContext_UpdatePending.
        ///  Default value: 'An update operation on the item is already in the queue.' 
        /// </summary>
        public static string SyncContext_UpdatePending { get { return @"An update operation on the item is already in the queue."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_UnterminatedStringLiteral.
        ///  Default value: 'The specified odata query has unterminated string literal.' 
        /// </summary>
        public static string ODataExpressionParser_UnterminatedStringLiteral { get { return @"The specified odata query has unterminated string literal."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_SyntaxError.
        ///  Default value: 'The specified odata query has syntax errors.' 
        /// </summary>
        public static string ODataExpressionParser_SyntaxError { get { return @"The specified odata query has syntax errors."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_DigitExpected.
        ///  Default value: 'Digit expected.' 
        /// </summary>
        public static string ODataExpressionParser_DigitExpected { get { return @"Digit expected."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_CloseParenOrCommaExpected.
        ///  Default value: '')' or ',' expected.' 
        /// </summary>
        public static string ODataExpressionParser_CloseParenOrCommaExpected { get { return @"')' or ',' expected."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_ExpressionExpected.
        ///  Default value: 'Expression expected.' 
        /// </summary>
        public static string ODataExpressionParser_ExpressionExpected { get { return @"Expression expected."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_OpenParenExpected.
        ///  Default value: ''(' expected.' 
        /// </summary>
        public static string ODataExpressionParser_OpenParenExpected { get { return @"'(' expected."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_SubstringArgsCount.
        ///  Default value: 'Function 'substring' requires 2 or 3 parameters.' 
        /// </summary>
        public static string ODataExpressionParser_SubstringArgsCount { get { return @"Function 'substring' requires 2 or 3 parameters."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_CloseParenOrOperatorExpected.
        ///  Default value: '')' or operator expected' 
        /// </summary>
        public static string ODataExpressionParser_CloseParenOrOperatorExpected { get { return @"')' or operator expected"; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_FunctionArgsCount.
        ///  Default value: 'Function '{0}' requires {1} parameter(s).' 
        /// </summary>
        public static string ODataExpressionParser_FunctionArgsCount { get { return @"Function '{0}' requires {1} parameter(s)."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_IdentifierExpected.
        ///  Default value: 'Expected identifier.' 
        /// </summary>
        public static string ODataExpressionParser_IdentifierExpected { get { return @"Expected identifier."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_IntegerLiteralExpected.
        ///  Default value: 'Expected integer literal.' 
        /// </summary>
        public static string ODataExpressionParser_IntegerLiteralExpected { get { return @"Expected integer literal."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_InvalidIntegerLiteral.
        ///  Default value: 'The specified odata query has invalid integer literal '{0}'.' 
        /// </summary>
        public static string ODataExpressionParser_InvalidIntegerLiteral { get { return @"The specified odata query has invalid integer literal '{0}'."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_InvalidRealLiteral.
        ///  Default value: 'The specified odata query has invalid real literal '{0}'.' 
        /// </summary>
        public static string ODataExpressionParser_InvalidRealLiteral { get { return @"The specified odata query has invalid real literal '{0}'."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_InvalidTypeCreation.
        ///  Default value: 'The specified odata query has invalid '{0}' type creation expression.' 
        /// </summary>
        public static string ODataExpressionParser_InvalidTypeCreation { get { return @"The specified odata query has invalid '{0}' type creation expression."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_RealLiteralExpected.
        ///  Default value: 'Expected real literal.' 
        /// </summary>
        public static string ODataExpressionParser_RealLiteralExpected { get { return @"Expected real literal."; } }
        /// <summary>
        ///  Localized value for ODataExpressionParser_StringLiteralExpected.
        ///  Default value: 'Expected string literal.' 
        /// </summary>
        public static string ODataExpressionParser_StringLiteralExpected { get { return @"Expected string literal."; } }
        /// <summary>
        ///  Localized value for SyncStore_FailedToDeleteOperation.
        ///  Default value: 'Failed to delete operation from the local store.' 
        /// </summary>
        public static string SyncStore_FailedToDeleteOperation { get { return @"Failed to delete operation from the local store."; } }
        /// <summary>
        ///  Localized value for SyncStore_FailedToReadItem.
        ///  Default value: 'Failed to read the item from local store.' 
        /// </summary>
        public static string SyncStore_FailedToReadItem { get { return @"Failed to read the item from local store."; } }
        /// <summary>
        ///  Localized value for SyncStore_FailedToLoadError.
        ///  Default value: 'Failed to read errors from the local store.' 
        /// </summary>
        public static string SyncStore_FailedToLoadError { get { return @"Failed to read errors from the local store."; } }
        /// <summary>
        ///  Localized value for SyncStore_FailedToDeleteError.
        ///  Default value: 'Failed to delete error from the local store.' 
        /// </summary>
        public static string SyncStore_FailedToDeleteError { get { return @"Failed to delete error from the local store."; } }
        /// <summary>
        ///  Localized value for SyncStore_OperationFailed.
        ///  Default value: 'Failed to perform operation on local store.' 
        /// </summary>
        public static string SyncStore_OperationFailed { get { return @"Failed to perform operation on local store."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_PullWithSelectNotSupported.
        ///  Default value: 'Pull query with select clause is not supported.' 
        /// </summary>
        public static string MobileServiceSyncTable_PullWithSelectNotSupported { get { return @"Pull query with select clause is not supported."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableOperation_ItemNotFound.
        ///  Default value: 'Operation must have an item associated with it.' 
        /// </summary>
        public static string MobileServiceTableOperation_ItemNotFound { get { return @"Operation must have an item associated with it."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_ItemNotFoundInStore.
        ///  Default value: 'Item not found in local store.' 
        /// </summary>
        public static string MobileServiceTable_ItemNotFoundInStore { get { return @"Item not found in local store."; } }
        /// <summary>
        ///  Localized value for MobileServiceTableOperation_ResultNotJObject.
        ///  Default value: 'Mobile Service table operation returned an unexpected response.' 
        /// </summary>
        public static string MobileServiceTableOperation_ResultNotJObject { get { return @"Mobile Service table operation returned an unexpected response."; } }
        /// <summary>
        ///  Localized value for SyncStore_NotInitialized.
        ///  Default value: 'The store must be initialized before it can be used.' 
        /// </summary>
        public static string SyncStore_NotInitialized { get { return @"The store must be initialized before it can be used."; } }
        /// <summary>
        ///  Localized value for SyncStore_AlreadyInitialized.
        ///  Default value: 'The store is already initialized.' 
        /// </summary>
        public static string SyncStore_AlreadyInitialized { get { return @"The store is already initialized."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_InvalidQueryId.
        ///  Default value: 'The query id must not contain pipe character and should be less than 50 characters in length.' 
        /// </summary>
        public static string MobileServiceSyncTable_InvalidQueryId { get { return @"The query id must not contain pipe character and should be less than 50 characters in length."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_IncrementalPullWithOrderNotAllowed.
        ///  Default value: 'Incremental pull query must not have orderby clause.' 
        /// </summary>
        public static string MobileServiceSyncTable_IncrementalPullWithOrderNotAllowed { get { return @"Incremental pull query must not have orderby clause."; } }
        /// <summary>
        ///  Localized value for SyncStore_FailedToUpdateOperation.
        ///  Default value: 'Failed to update operation in the local store.' 
        /// </summary>
        public static string SyncStore_FailedToUpdateOperation { get { return @"Failed to update operation in the local store."; } }
        /// <summary>
        ///  Localized value for SyncError_OperationUpdated.
        ///  Default value: 'The operation has been updated and cannot be cancelled.' 
        /// </summary>
        public static string SyncError_OperationUpdated { get { return @"The operation has been updated and cannot be cancelled."; } }
        /// <summary>
        ///  Localized value for SyncContext_PurgeOnDirtyTable.
        ///  Default value: 'The table cannot be purged because it has pending operations.' 
        /// </summary>
        public static string SyncContext_PurgeOnDirtyTable { get { return @"The table cannot be purged because it has pending operations."; } }
        /// <summary>
        ///  Localized value for SyncContext_InsertAttempted.
        ///  Default value: 'The item is in inconsistent state in the local store. Please complete the pending sync by calling PushAsync()before deleting the item.' 
        /// </summary>
        public static string SyncContext_InsertAttempted { get { return @"The item is in inconsistent state in the local store. Please complete the pending sync by calling PushAsync()before deleting the item."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_IncrementalPullWithSkipTopNotSupported.
        ///  Default value: 'Incremental pull query must not have skip or top specified.' 
        /// </summary>
        public static string MobileServiceSyncTable_IncrementalPullWithSkipTopNotSupported { get { return @"Incremental pull query must not have skip or top specified."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_SkipNotAllowed.
        ///  Default value: 'The supported table options does not include skip. ' 
        /// </summary>
        public static string MobileServiceSyncTable_SkipNotAllowed { get { return @"The supported table options does not include skip. "; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_TopNotAllowed.
        ///  Default value: 'The supported table options does not include top.' 
        /// </summary>
        public static string MobileServiceSyncTable_TopNotAllowed { get { return @"The supported table options does not include top."; } }
        /// <summary>
        ///  Localized value for MobileServiceSyncTable_OrderByNotAllowed.
        ///  Default value: 'The supported table options does not include orderby.' 
        /// </summary>
        public static string MobileServiceSyncTable_OrderByNotAllowed { get { return @"The supported table options does not include orderby."; } }
        /// <summary>
        ///  Localized value for MobileServiceTable_QueryUriHostIsDifferent.
        ///  Default value: 'The query uri must be on the same host as the Mobile Service.' 
        /// </summary>
        public static string MobileServiceTable_QueryUriHostIsDifferent { get { return @"The query uri must be on the same host as the Mobile Service."; } }
        /// <summary>
        ///  Localized value for WP8LoginPage_MustBeCalledFromAuthBroker.
        ///  Default value: 'This page must be called from the type '{0}'.' 
        /// </summary>
        public static string WP8LoginPage_MustBeCalledFromAuthBroker { get { return @"This page must be called from the type '{0}'."; } }
        /// <summary>
        ///  Localized value for Pull_Cannot_Use_Reserved_Key.
        ///  Default value: 'The key '{0}' is reserved and cannot be specified as a query parameter.' 
        /// </summary>
        public static string Pull_Cannot_Use_Reserved_Key { get { return @"The key '{0}' is reserved and cannot be specified as a query parameter."; } }
        /// <summary>
        ///  Localized value for Push_Failure.
        ///  Default value: 'Push operation has failed. See the PushResult for details.' 
        /// </summary>
        public static string Push_Failure { get { return @"Push operation has failed. See the PushResult for details."; } }
         
    }
}